apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: checkpodrepo
spec:
  crd:
    spec:
      names:
        kind: checkpodrepo
      validation:
        openAPIV3Schema:
          type: object
          properties:
            repos:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package checkpodrepo

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image, repo)]
          not any(satisfied)

          msg := sprintf("Container image <%v> not in <%v> repo", [container.image, input.parameters.repos])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.initContainers[_]
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image, repo)]
          not any(satisfied)

          msg := sprintf("Init container image <%v> not in <%v> repo", [container.image, input.parameters.repos])
        }
